[package]
name = "rpysight"
version = "0.1.0"
authors = ["HagaiHargil <hagaihargil@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kiss3d = "0.30"
nalgebra-numpy = { git = "https://github.com/PBLab/nalgebra-numpy.git" }
rand = "0.8.3"
pyo3 = { version = "0.11.1", features=['extension-module'] }
nalgebra = "0.25"
arrow = "3.0.0"

[dev-dependencies]
numpy = "0.11"

[lib]
name = "librpysight"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "rpyrender"
path = "src/bin.rs"

[package.metadata.maturin]
requires-dist = ["ipython>=7", "numpy>=1.19", "pandas>=1.2", "numba>=0.51", "pytest>=6.2", "matplotlib>=3.3", "pyarrow>=3.0.0",]
classifier = ["Programming Language :: Python", "Programming Language :: Rust"]
maintainer = "Hagai Har-Gil"
