[package]
name = "rpysight"
version = "0.1.0"
authors = ["HagaiHargil <hagaihargil@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kiss3d = "0.30"
nalgebra = { version = "0.25", features = ["serde-serialize"] }
pyo3 = { version = "0.13", features = ["extension-module"] }
arrow = "3.0.0"
thiserror = "1.0"
anyhow = "1.0"
iced = { version = "0.3", features = ["image"] }
log = "0.4"
simplelog = "0.10"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
directories = "3.0"
rand = "0.8"

[lib]
name = "librpysight"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "rpyrender"
path = "src/bin.rs"

[package.metadata.maturin]
requires-dist = ["ipython>=7", "numpy>=1.19", "pandas>=1.2", "pytest>=6.2", "matplotlib>=3.3", "pyarrow>=3.0.0", "toml > 0.10",]
classifier = ["Programming Language :: Python", "Programming Language :: Rust"]
maintainer = "Hagai Har-Gil"
